sudo: false
language: node_js
node_js:
  - 7
script:
  - node_modules/.bin/handroll src/cli.coffee --cjs --dest lib/cli.js
  - node_modules/.bin/handroll src/index.coffee --cjs --dest lib/shortcake.js
  - node_modules/.bin/shortcake build
  - node_modules/.bin/shortcake test
cache:
  directories:
    - node_modules
